Javascript/notes/django/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.password, name='password'),
]

Javascript/notes/django/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/like/', views.like, name='like'),
    path('<int:article_pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:article_pk>/follow/<int:user_pk>/', views.follow, name='follow'),
]

Javascript/notes/django/review/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
]

Javascript/notes/django/articles/models.py
from django.db import models
from django.conf import settings


class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    liked_users = models.ManyToManyField( # article.liked_users.all() => 아티클을 좋아하는 모든 유저
        settings.AUTH_USER_MODEL, 
        related_name='liked_articles', # user.liked_articles.all() => 유저가 좋아하는 모든 아티클
    )

    class Meta:
        ordering = ('-pk', )


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='comments', on_delete=models.CASCADE)
    article = models.ForeignKey(Article, related_name='comments', on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-pk', )

Javascript/notes/django/articles/forms.py
from django import forms
from .models import Article, Comment


class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = ['title', 'content', ]


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['content', ]
        # exclude = ['article', ]

Javascript/notes/django/articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST, require_GET
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.http import HttpResponse, JsonResponse
from .models import Article, Comment
from .forms import ArticleForm, CommentForm


@require_GET
def index(request):
    articles = Article.objects.all()
    context = {'articles': articles}
    return render(request, 'articles/index.html', context)


@require_GET
def detail(request, article_pk):
    # 사용자가 url 에 적어보낸 article_pk 를 통해 디테일 페이지를 보여준다.
    article = get_object_or_404(Article, pk=article_pk)
    comment_form = CommentForm()
    comments = article.comments.all()
    context = {
        'article': article,
        'comment_form': comment_form,
        'comments': comments,
    }
    return render(request, 'articles/detail.html', context)


@login_required
def create(request):
    if request.method == 'POST':
        # Article 을 생성해달라고 하는 요청
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('articles:detail', article.pk)
    else: # GET
        # Article 을 생성하기 위한 페이지를 달라고 하는 요청
        form = ArticleForm()
    context = {'form': form}
    return render(request, 'articles/create.html', context)


@login_required
def update(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if article.user == request.user:
        if request.method == 'POST':
            form = ArticleForm(request.POST, instance=article)
            if form.is_valid():
                form.save()
                return redirect('articles:detail', article_pk)
        else: # GET method
            form = ArticleForm(instance=article)
    else:
        return redirect('articles:detail', article_pk)
    context = {'form': form}
    return render(request, 'articles/update.html', context)


@require_POST
def delete(request, article_pk):
    if request.user.is_authenticated:
        # article_pk 에 맞는 article 을 꺼낸다. 삭제한다.
        article = get_object_or_404(Article, pk=article_pk)
        if article.user == request.user:
            article.delete()
        else:
            return redirect('articles:detail', article_pk)
    return redirect('articles:index')


# 댓글을 생성하는 요청을 받는다.
@require_POST
def comments_create(request, article_pk):
    if request.user.is_authenticated:
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.article_id = article_pk
            comment.user = request.user
            comment.save()
    return redirect('articles:detail', article_pk)


@require_POST
def comments_delete(request, article_pk, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        if comment.user == request.user:
            comment.delete()
        return redirect('articles:detail', article_pk)
    return HttpResponse('You are Unauthorized', status=401)


def like(request, article_pk):
    user = request.user
    article = get_object_or_404(Article, pk=article_pk)

    # if article.liked_users.filter(pk=user.pk).exists(): # 1개의 데이터라도 존재하면 True
    if user in article.liked_users.all():
        user.liked_articles.remove(article)
        # Axios
        liked = False
    else:
        user.liked_articles.add(article)
        liked = True
    
    context = {
        'liked': liked, 
        'count': article.liked_users.count(),
        }

    return JsonResponse(context)


@login_required
def follow(request, article_pk, user_pk):
    # 로그인한 유저가 게시글 유저를 Follow or Unfollow 한다.
    user = request.user # 로그인 유저
    person = get_object_or_404(get_user_model(), pk=user_pk) # 게시글 주인

    if user in person.followers.all(): # 이미 팔로워임
        person.followers.remove(user) # 언팔하겠음
    else: # 팔로워가 아님
        person.followers.add(user) # 팔로우 하겠음
    
    return redirect('articles:detail', article_pk)

Javascript/notes/django/articles/templates/articles/_follow.html
<div class="jumbotron text-center text-white bg-dark">
  <p class="lead mb-1">작성자 정보</p>
  <h1 class="display-4">{{ article.user.username }}</h1>
  <hr>
  <p class="lead">
    팔로잉 : {{ article.user.followings.all|length }} / 
    팔로워 : {{ article.user.followers.all|length }}
  </p>

  {% if user != article.user %}
    {% if user in article.user.followers.all %}
    <a href="{% url 'articles:follow' article.pk article.user.pk %}" class="btn btn-primary btn-lg">Unfollow</a>
    {% else %}
    <a href="{% url 'articles:follow' article.pk article.user.pk %}" class="btn btn-primary btn-lg">Follow</a>
    {% endif %}
  {% endif %}
</div>

Javascript/notes/django/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block title %}Article::Create{% endblock title %}

{% block container %}
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">생성하기</button>
</form>
{% endblock container %}

Javascript/notes/django/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %}Article::Detail{% endblock title %}

{% block container %}
<h2>{{ article.title }}</h2>
<p>{{ article.created_at }}</p>
<p>작성자: {{ article.user }}</p>
{% comment %} Aixos 사용하여 동적으로 변경 {% endcomment %}
{% comment %} <a href="{% url 'articles:like' article.pk %}">
  {% if user in article.liked_users.all %}
  <i class="fas fa-heart fa-lg" style="color: red"></i>
  {% else %}
  <i class="far fa-heart fa-lg" style="color: red"></i>
  {% endif %}
</a> {% endcomment %}

{% comment %} 아래와 같이 class {% endcomment %}
{% comment %} data-id => 어느 포스트에 좋아요를 누를건지 적어서 보낸다 {% endcomment %}
<i
  class="{% if user in article.liked_users.all %}fas{% else %}far{% endif %} fa-heart fa-lg" 
  id="like-btn" 
  data-id="{{ article.pk }}" 
  style="color:red"
>
</i>


<p><span id="like-count">{{ article.liked_users.all | length }}</span>명이 이 글을 좋아합니다.</p>
<hr>
<p>{{ article.content }}</p>
<hr>
{% if article.user == request.user %}
<a href="{% url 'articles:update' article.pk %}">[수정하기]</a>
<form action="{% url 'articles:delete' article.pk %}" method="post">
  {% csrf_token %}
  <button type="submit">삭제하기</button>
</form>
<hr>
{% endif %}
<h3>Comments</h3>
{% if user.is_authenticated %}
<form action="{% url 'articles:comments_create' article.pk %}" method="post">
  {% csrf_token %}
  {{ comment_form.as_table }}
  <button type="submit">작성하기</button>
</form>
{% endif %}
<hr>
<ul>
{% for comment in comments %}
  <li>
    {% if request.user == comment.user %}
    <form action="{% url 'articles:comments_delete' article.pk comment.pk %}" method="post">
      {% csrf_token %}
      <span>{{ comment.content }} - {{ comment.created_at }} / {{ comment.user }}</span>
      <button class="btn btn-danger" type="submit">삭제하기</button>
    </form>
    {% else %}
    <span>{{ comment.content }} - {{ comment.created_at }} / {{ comment.user }}</span>
    {% endif %}
  </li>
{% endfor %}
</ul>

{% include 'articles/_follow.html' %}

<script>
const likeBtn = document.querySelector('#like-btn')
likeBtn.addEventListener('click', function(event) {
  // Button의 data-id 속성을 아래 코드로 가지고 온다.
  const articleId = event.target.dataset.id
  axios.get(`/articles/${articleId}/like/`)
  .then(function(response){
    // console.log(response)
    // 사용자의 좋아요 상태에 따라 버튼 클래스 변경
    if (response.data.liked) {
      // 응답받았을때 사용자가 article을 좋아요인 상태라면,
      // classList => likeBtn의 class 목록
      likeBtn.classList.remove('far')
      likeBtn.classList.add('fas')
    } else {
      likeBtn.classList.remove('fas')
      likeBtn.classList.add('far')
    }
    // 아티클을 좋아하는 사람들 수를 응답받아 적용
    const likeCount = document.querySelector('#like-count')
    likeCount.innerText = response.data.count
  })
})
</script>


{% endblock container %}

Javascript/notes/django/articles/templates/articles/index.html
{% extends 'base.html' %}


{% block title %}Article::Index{% endblock title %}

{% block container %}
<h2>Article List</h2>
{% if user.is_authenticated %}
<a href="{% url 'articles:create' %}">[생성하기]</a>
{% else %}
<a href="{% url 'accounts:signup' %}">게시글을 작성하기 위해 지금 저희의 회원이 되어보세요!</a>
{% endif %}


<hr>
{% for article in articles %}
<div>
  <h3>{{ article.pk }}. {{ article.title }}</h3>
  <p>작성자: {{ article.user }}</p>
  <a href="{% url 'articles:detail' article.pk %}">[상세보기]</a>
</div>
<br>
{% endfor %}

{% endblock container %}

Javascript/notes/django/articles/templates/articles/update.html
{% extends 'base.html' %}

{% block title %}Article::Update{% endblock title %}

{% block container %}
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">수정하기</button>
</form>
{% endblock container %}